<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-06-26T22:15:38 IST" name="Suite" finished-at="2024-06-26T22:15:52 IST" duration-ms="13831">
    <groups>
    </groups>
    <test started-at="2024-06-26T22:15:38 IST" name="Test" finished-at="2024-06-26T22:15:52 IST" duration-ms="13831">
      <class name="TestCases.QaLegend_TestCases">
        <test-method is-config="true" signature="intialization()[pri:0, instance:TestCases.QaLegend_TestCases@2e6a8155]" started-at="2024-06-26T22:15:39 IST" name="intialization" finished-at="2024-06-26T22:15:45 IST" duration-ms="6480" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- intialization -->
        <test-method signature="sendAMessage()[pri:0, instance:TestCases.QaLegend_TestCases@2e6a8155]" started-at="2024-06-26T22:15:45 IST" name="sendAMessage" finished-at="2024-06-26T22:15:52 IST" duration-ms="7192" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Testmessage3142] but found [Devika M
Today at 04:45 pm]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Testmessage3142] but found [Devika M
Today at 04:45 pm]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at TestCases.QaLegend_TestCases.sendAMessage(QaLegend_TestCases.java:83)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sendAMessage -->
      </class> <!-- TestCases.QaLegend_TestCases -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
